"""
podcast_schema.py
-----------------
Pydantic models defining the request/response contracts for the
podcast_agent API layer.

All models use strict typing and field-level validation to ensure
data integrity at the API boundary. These schemas are the single
source of truth for serialisation and OpenAPI documentation.
"""

from pydantic import BaseModel, Field
from typing import Any


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------

class PodcastGenerateRequest(BaseModel):
    """
    Request body for the POST /generate-podcast endpoint.

    Attributes:
        pdf_path (str): Server-side path (or uploaded file reference) to the
                        source PDF document used as podcast content.
        top_k (int):    Number of chunks to retrieve for context. Defaults to
                        the value configured in settings.
    """

    pdf_path: str = Field(
        ...,
        description="Absolute server-side path to the source PDF file.",
        example="/data/papers/attention_is_all_you_need.pdf",
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of top retrieved chunks to use as LLM context.",
    )


# ---------------------------------------------------------------------------
# Response Models
# ---------------------------------------------------------------------------

class PodcastGenerateResponse(BaseModel):
    """
    Response body returned by the POST /generate-podcast endpoint.

    Attributes:
        plan       (str):      The structural episode plan produced by the Planner Agent.
        script     (str):      The final reviewed podcast script (two-host dialogue).
        audio_path (str):      File-system path to the merged output audio file.
        critic     (str):      The Critic Agent's final evaluation verdict.
        metadata   (dict):     Supplementary metadata (e.g. chunk count, model used).
    """

    plan: str = Field(..., description="Episode outline generated by the Planner Agent.")
    script: str = Field(..., description="Final two-host podcast script.")
    audio_path: str = Field(..., description="Path to the merged podcast audio file.")
    critic: str = Field(..., description="Critic Agent's quality verdict for the script.")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Supplementary pipeline metadata (chunk count, models used, etc.).",
    )
